/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function TestModel(props) {
  const { nodes, materials } = useGLTF("model/test.glb");
  console.log(materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["0"]}
        position={[-0.44, 5, -0.22]}
        scale={[1, 0.2, 0.4]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials["1"]}
        position={[-1.71, 1.19, 2.12]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials["2"]}
        position={[-0.55, -0.28, 1.52]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials["3"]}
        position={[-0.75, 2.64, -1.7]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials["4"]}
        position={[0.94, 0.31, -2.35]}
      />
    </group>
  );
}

useGLTF.preload("model/test.glb");
